### ISSUE TITLE
bug: Types not working with typescript 4.8

### ISSUE THREAD

**Issue by Didas-git** [sapphiredev/shapeshift#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

With the new changes to the `{}` type, sapphire is throwing errors when compiling.

### Steps To Reproduce

1. Update to typescript 4.8
2. Run tsc

### Expected behavior

Not throwing an error.

### Screenshots

![unknown-38](https://user-images.githubusercontent.com/80978939/187006107-6a6507aa-30b3-443b-9944-359baf411c5d.png)

**Comment by imranbarbhuiya** [comment]
The `SchemaOf` issue is easily fixable by adding `extends NonNullable` in `SchemaOf` but I tried to fix other type issues related to `{}` and I wasn't able to do it. The issue is coming from https://github.com/sapphiredev/shapeshift/blob/main/src/lib/util-types.ts#L10 
before 4.8, it was `{} & object` but after 4.8, it's now `object`. The only solution which worked for me was by removing `extends NonNullableObject` from https://github.com/sapphiredev/shapeshift/blob/main/src/validators/ObjectValidator.ts#L15 but that's not a solution as it'll now accept any values

**Comment by Didas-git** [comment]
> The `SchemaOf` issue is easily fixable by adding `extends NonNullable` in `SchemaOf` but I tried to fix other type issues related to `{}` and I wasn't able to do it. The issue is coming from https://github.com/sapphiredev/shapeshift/blob/main/src/lib/util-types.ts#L10 before 4.8, it was `{} & object` but after 4.8, it's now `object`. The only solution that worked for me was removing `extends NonNullableObject` from https://github.com/sapphiredev/shapeshift/blob/main/src/validators/ObjectValidator.ts#L15 but that's not a solution as it'll now accept any values.
> 
> For now you can add `skipLibCheck` in your tsconfig or use `typescript < 4.8`

I have been using skipLibCheck because of this, but its not the best thing to do.
About `object`, maybe a solution to this would be using `Record<PropertyKey, unknown>` which can be used to represent any object but *might* need some changes in other parts of the code.
