### ISSUE TITLE
question: Multiple errors causing my discord bot to crash

### ISSUE THREAD

**Issue by DJ45X** [sapphiredev/shapeshift#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I'm not quite sure what's really going on. Sapphire is being called as a dependency by the discord.js package. This has been happening often and I'm not sure what I  can do about it. I've tried getting support from the discord.js folks and they haven't been helpful. You can review the errors [here](https://srcshare.io/645d3c3dcf564d4d2b6fee25).

### Steps To Reproduce

I don't have any steps. I only know that when an `interactionCreate` event is fired in my discord bot, the above error occurs. 

### Expected behavior

No crashing? I'm not quite sure what sapphire is even for. Just know that it's a dependency for discord.js. 

### Additional context

I'm still new to making discord bots using discord.js. And still pretty new to javascript in general. So I'm not really sure what the next steps in diagnosing this issue. But my bot is highly unstable due to this issue and I need to figure out how to mitigate the crashing.

**Comment by favna** [comment]
`@discordjs/builders` has a dependency of `@sapphire/shapeshift` to provide input validation. That is to say, whatever you're inputting is invalid and if Shapeshift wouldn't throw an error then the Discord API would. You are self responsible for handling your errors and ensuring your bot doesn't crash due to them.

The error says it comes from `EmbedBuilder.addFields` and at the bottom it says `[ 'value', [ExpectedConstraintError]` which means that you're not providing the field value. Read up on how to create embeds with DiscordJS on their guide: https://discordjs.guide/popular-topics/embeds.html#using-the-embed-constructor

---

As for this:
> I'm not quite sure what sapphire is even for
Sapphire is primarily the only officially supported framework for DiscordJS. We also have many tools, such as shapeshift. In fact, some of our other libraries are also dependencies for DiscordJS such as `@sapphire/bitfield`, `@sapphire/snowflake`, and `@sapphire/async-queue`. We also have our own server: https://discord.gg/sapphiredev.

Lastly, I assume you asked for support in the `djs-help-14` channel? I'm honestly trying to find where you asked and see how people replied that didn't help you because it would be good to get people to provide better support so you didn't have to go through the hoops of creating a GH issue.

**Comment by favna** [comment]
Closing this as answered above and questions are supposed to go through Discord, not GitHub issues.
